### PR TITLE
Fix several announcement issues like #2222 and more

### PR DESCRIPTION
**Pull request by jderriks**
Prevent Teachers Spam. Select ALL is you want to mail everyone.

### CODE REVIEW

**Comment by ywarnier** [comment]
@jmontoyaa I don't see that your commit solves the issue mentioned in #2226 about the order of users in the left list.

**Comment by ywarnier** [comment]
This PR, however, does fix the issue. Please review and merge.

**Comment by jmontoyaa** [comment]
@ywarnier The problem with this PR is that it was added for 2 different issues.
The token issue was fixed. I cannot reproduce the error.

**Comment by jmontoyaa** [comment]
I just added a fix for that select ordering.

**Comment by ywarnier** [comment]
Now I'm good. Thanks.

**Pull request closed without merging**
