### PR TITLE
Fixed incorrect method api_get_course_info_by_id

### PR DESCRIPTION
**Pull request by danilobrinu**
Change api_get_course_info_by_id to api_get_course_info -> $courseId is a course code not the index of course

### CODE REVIEW

**Comment by ywarnier** [comment]
You spotted an issue, indeed, but your solution isn't complete. The course_rel_user table is now based on the c_id (int) and not the course_code (as it was in 1.9). As such, there is a need for a "translation" of the contents of $csv_subscription to use the c_id instead of the course_code, or to recover the course_code instead of the c_id inside of $db_subscription. At the moment, one array is based on code, the other on ID, so the array_diff() will always return the full array.
So I cannot accept your PR as it is right now, but if you change the course_rel_user query to join on the course table and get the course_code instead of the c_id, I will.

**Comment by danilobrinu** [comment]
Ohh i use 1,10.x and have a issue. I fixed change method api_get_course_info_by_id  to api_get_course_info

**Comment by jmontoyaa** [comment]
I just applied a fix.

**Comment by ywarnier** [comment]
@danilobrinu this should fix the issue you had. If you get a chance to review this and confirm it fixes the problem you had, we would be very glad...

**Comment by danilobrinu** [comment]
Yes @ywarnier. I fixed issue using api_get_course_info insted to api_get_course_info_by_id in my version thx to accepted my PR.

**Pull request closed without merging**
