### PR TITLE
Upgrade to WebcamJS from JPEGCam in Document Tools - Refs #7181

### PR DESCRIPTION
**Pull request by jloguercio**

### CODE REVIEW

**Comment by ywarnier** [comment]
This PR is OK (reviewed quickly) but we will wait after 1.10.0 to integrate it because it removes the Flash plugin and this might affect IE browsers that do not support WebRTC (or is there a solution for that as well?)

**Comment by jloguercio** [comment]
It doesn't removes Flash plugin, it only uses the the native video api and if it doesn't support that feature it falls to Flash.

Also, in code, you can force to Flash.

**Comment by ywarnier** [comment]
Then it's OK for me.

**Comment by jloguercio** [comment]
image

Tested in IExplorer, works well, it falls to Flash

**Comment by ywarnier** [comment]
Please update your PR to make it against 1.10.x branch. We will add it to 1.10.0 :-)

**Comment by ywarnier** [comment]
Closing as it has already been merged into 1.10.x

**Pull request closed without merging**
