### PR TITLE
Update stats.php

### PR DESCRIPTION
**Pull request by oktavianto**
remove student can view stats.php (allow student to see the correct answer).

### CODE REVIEW

**Comment by ywarnier** [comment]
Thank you for your contribution!
I think this is incorrect (as it will remove access to the whole script). Seeing the right answer should be controlled by the settings of the exercise.
But we'll review that and come back to you.

**Comment by jmontoyaa** [comment]
Good eye. Added to 1.11.x

**Comment by ywarnier** [comment]
That still doesn't look like it cares about the exercise settings :-)

**Comment by jmontoyaa** [comment]
Which exercise settings? That page is only to see stats about an exercise. Only available for teachers ...

**Comment by ywarnier** [comment]
That answers my question then... :-)

**Pull request closed without merging**
