### PR TITLE
Add an option to hide teachers list

### PR DESCRIPTION
**Pull request by SatyanJ**
## Resume
Courses list can get very long when there is a lot of teachers displayed. This feature allows to hide the teachers from the teachers list.
In the current version, an admin option already exists but this allow each user to hide/show the teachers list in their profile. 
## Screenshots
screenshot from 2017-04-21 23-24-44
screenshot from 2017-04-21 23-25-08
## How to use it
Since I can't change the database between minor versions, I added this feature as a dormant feature that can be activated by adding a extra fields for users in Admin/Profils with the following settings: 
image
## Migration file
A migration file was created in order to add the necessary changes in the database for v2.0. 

(cc @moy, @Polycapa)

### CODE REVIEW

**Comment by SatyanJ** [comment]
The codeclimate tests timeout. 
Concerning, Travis-CI, it is `The command "sudo apt-get update" failed and exited with 100 during .`, could it be due to the migration file ?

**Comment by moy** [comment]
> The command "sudo apt-get update" failed and exited with 100 during

This is the installation step (Travis's build job start with an essentially empty container and lets you install stuff inside), probably unrelated to anything Chamilo-related. If you look carefully, the failure occurs when trying to get the index for the Chrome repository.

This kind of thing typically happens when there's a temporary network error between Travis and the Ubuntu mirrors (or when the mirror is down for some reason). My experience is that restarting the job later just works.

**Comment by jmontoyaa** [comment]
Travis builds are failing because this change:

https://github.com/chamilo/chamilo-lms/commit/65188b0510bf1116540c4bca5ff115415a8878f9

**Comment by jmontoyaa** [comment]
I just restarted the travis build for php7.

1.11.x travis builds are working well, but is failing because behat tests.

**Comment by jmontoyaa** [comment]
I found the fix of that apt update

https://github.com/chamilo/chamilo-lms/commit/8db557c66f7c796fa0f412767a082225dceb4b6d

**Comment by ywarnier** [comment]
@SatyanJ considering this will only be included for v2.0 of Chamilo, could you please resubmit this PR against the master branch?

**Comment by SatyanJ** [comment]
@ywarnier 
I'll have to make the changes on the master branch instead of the 1.11.x. 
It should be coming on the evening.

**Comment by ywarnier** [comment]
OK, no hurry.

**Comment by ywarnier** [comment]
If it's easier for you we can also leave this PR open until we retake more actively the development on the master branch (which includes merging 1.11.x with master, which might make your PR change easier)

**Comment by SatyanJ** [comment]
I'll take a look, if the changes I've made to the 1.11.x are as easy to put in 2.0.

**Comment by jmontoyaa** [comment]
I will do a merge of 1.11.x to master. Because master now is very outdated.

**Comment by SatyanJ** [comment]
@jmontoyaa I guess I'll wait until the merge. 
I had already added some issues and PR for the master branch which I don't think would have been fix by the merge. ( now I don't think it was a good idea to add those right after the minor version release)

**Comment by jmontoyaa** [comment]
I sent yesterday a merge of 1.11.x to master. There could be some things that are broken.
I have to check the installation process again and setup travis.

**Comment by SatyanJ** [comment]
I'm closing this PR and making another one. 
(I cherry-picked the modifications I've made on master branch, just need to test if it's working)

@jmontoyaa

**Pull request closed without merging**
