### PR TITLE
Add follow redirect in bigbluebutton plugin.

### PR DESCRIPTION
**Pull request by GhaziTriki**

### CODE REVIEW

**Comment by GhaziTriki** [comment]
@jmontoyaa can't this PR be merged?

**Comment by ywarnier** [comment]
@GhaziTriki any objection to me adding a:
```
curl_setopt( $ch, CURLOPT_MAXREDIRS, 5 );
```
?
I'm worried about the possibility of recursive loops.

**Comment by ywarnier** [comment]
ping @GhaziTriki

**Comment by GhaziTriki** [comment]
@ywarnier Sure !

**Pull request merged**
