### PR TITLE
Fix hotspot creation issue when relpath not empty …

### PR DESCRIPTION
**Pull request by baelmyhu**
See https://support.chamilo.org/issues/8027

### CODE REVIEW

**Comment by AngelFQC** [comment]
Hi, Hubert
Please change, in JS for the ```config``` object, the property name from ```relPath```  to ```relpath```

**Comment by baelmyhu** [comment]
Is it the camel case naming the problem ?

**Comment by AngelFQC** [comment]
The commit in this PR was added by cherry-pick for @jloguercio 
@baelmyhu is the hotspot question type ok?

**Comment by ywarnier** [comment]
Closing for lack of feedback. The fix in this PR has already been included through another PR. Thanks.

**Pull request closed without merging**
