### PR TITLE
add extraheader for email editor & add chart js for session graph

### PR DESCRIPTION
**Pull request by hichamon306**
capture d ecran 2019-01-27 a 23 43 00
In this pull request I fix used email for email_editor page, I also add extra header  'reply_to' with name and email of current user.
I suggest also in this PR to replace existing graph for session progress, i replace it with chart js lib.
feel free if you have any comment.

Thanks 
Hicham

### CODE REVIEW

**Comment by ywarnier** [comment]
@hichamon306 I accepted this PR, but please send future PR separately (or at minimum separate commits) when you send code for 2 different things. This allows us to better manage code changes.
One commit must always be for one specific type of change. Mixing charts and emails here in the same commit should normally not be allowed. It is here because you're starting with PRs with us :wink:

**Comment by ywarnier** [comment]
I have also applied it to the master branch.

**Comment by hichamalaoui05** [comment]
Thank you Yanick, I'll take your remarks in consideration for the next PRs. :-)

**Comment by hichamon306** [comment]
Thank you Yanick, I'll take your remarks in consideration for the next PRs. :-)

**Pull request merged**
