### PR TITLE
SSO Okta integration saml

### PR DESCRIPTION
**Pull request by FraGoTe**
This is a new SSO Integration using SAML sponsored by www.open-source-company.de and developed by www.fragote.com

### CODE REVIEW

**Comment by jmontoyaa** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3173
           

Complexity increasing per file
==============================
- main/auth/simplesamlphp/modules/core/lib/Auth/Process/AttributeLimit.php  10
- main/auth/simplesamlphp/modules/cron/hooks/hook_configpage.php  1
- main/auth/simplesamlphp/modules/core/lib/Auth/UserPassOrgBase.php  6
- main/auth/simplesamlphp/lib/SimpleSAML/XHTML/TemplateLoader.php  3
- main/auth/simplesamlphp/modules/core/www/idp/logout-iframe.js  7
- main/auth/simplesamlphp/modules/core/lib/Auth/Source/AdminPassword.php  4
- main/auth/simplesamlphp/modules/core/lib/Auth/Process/ScopeAttribute.php  9
- main/auth/simplesamlphp/lib/SimpleSAML/XML/Errors.php  3
- main/auth/simplesamlphp/lib/SimpleSAML/Auth/ProcessingFilter.php  3
- main/auth/simplesamlphp/lib/SimpleSAML/HTTP/Router.php  4
- main/auth/simplesamlphp/lib/SimpleSAML/Utils/Auth.php  3
- main/auth/simplesamlphp/lib/SimpleSAML/Stats/Output.php  1
- main/auth/simplesamlphp/www/resources/script.js  2
- main/auth/simplesamlphp/lib/SimpleSAML/Error/AuthSource.php  1
- main/auth/simplesamlphp/tests/lib/SimpleSAML/Auth/TimeLimitedTokenTest.php  1
- main/auth/simplesamlphp/modules/core/lib/Auth/Process/WarnShortSSOInterval.php  4
- main/auth/simplesamlphp/tests/modules/core/lib/Auth/Process/AttributeRealmTest.php  1
- main/auth/simplesamlphp/lib/SimpleSAML/Utils/Config/Metadata.php  21
- main/auth/simplesamlphp/lib/SimpleSAML/Utils/EMail.php  12
- main/auth/simplesamlphp/lib/SimpleSAML/Utils/Config.php  4
- main/auth/simplesamlphp/tests/lib/SimpleSAML/DatabaseTest.php  1
- main/auth/simplesamlphp/lib/SimpleSAML/XML/Parser.php  4
- main/auth/simplesamlphp/tests/lib/SimpleSAML/Locale/LanguageTest.php  1
- main/auth/simplesamlphp/lib/SimpleSAML/XML/Validator.php  15
- main/auth/simplesamlphp/lib/SimpleSAML/Configuration.php  16
- main/auth/simplesamlphp/lib/SimpleSAML/SessionHandlerPHP.php  9
- main/auth/simplesamlphp/lib/SimpleSAML/XML/Signer.php  7
- main/auth/simplesamlphp/webpack.config.js  5
- main/auth/simplesamlphp/tests/lib/SimpleSAML/XML/SignerTest.php  1
- main/auth/simplesamlphp/lib/SimpleSAML/Utils/Attributes.php  8
- main/auth/simplesamlphp/modules/core/lib/Auth/Process/AttributeMap.php  8
- main/auth/simplesamlphp/tests/modules/core/lib/Auth/UserPassBaseTest.php  1
- main/auth/simplesamlphp/tests/lib/SimpleSAML/ConfigurationTest.php  4
- main/auth/simplesamlphp/tests/www/RouterTest.php  6
- main/auth/simplesamlphp/modules/core/lib/Controller/Redirection.php  8
- main/auth/simplesamlphp/lib/SimpleSAML/Logger/ErrorLogLoggingHandler.php  2
- main/auth/simplesamlphp/lib/SimpleSAML/Error/ErrorCodes.php  1
- main/auth/simplesamlphp/lib/SimpleSAML/Error/MetadataNotFound.php  1
- main/auth/simplesamlphp/tests/Utils/TestAuthSourceFactory.php  1
- main/auth/simplesamlphp/lib/SimpleSAML/Auth/AuthenticationFactory.php  1
- main/auth/simplesamlphp/lib/SimpleSAML/XML/Shib13/AuthnResponse.php  14
- main/auth/simplesamlphp/tests/lib/SimpleSAML/Locale/LocalizationTest.php  1
- main/auth/simplesamlphp/lib/SimpleSAML/IdP/TraditionalLogoutHandler.php  3
- main/auth/simplesamlphp/modules/core/lib/Auth/Process/StatisticsWithAttribute.php  6
- main/auth/simplesamlphp/modules/core/lib/Stats/Output/Log.php  2
- main/auth/simplesamlphp/tests/Utils/ExitTestException.php  1
- main/auth/simplesamlphp/lib/SimpleSAML/Metadata/MetaDataStorageSource.php  9
- main/auth/simplesamlphp/lib/_autoload_modules.php  8
- main/auth/simplesamlphp/modules/core/lib/Auth/UserPassBase.php  5
- main/auth/simplesamlphp/modules/cron/lib/Controller/Cron.php  6
- main/auth/simplesamlphp/lib/SimpleSAML/Stats.php  4
- main/auth/simplesamlphp/tests/modules/core/lib/Auth/Process/ScopeFromAttributeTest.php  1
- main/auth/simplesamlphp/tests/lib/SimpleSAML/Utils/NetTest.php  1
- main/auth/simplesamlphp/lib/SimpleSAML/Error/UserAborted.php  1
- main/auth/simplesamlphp/lib/SimpleSAML/Memcache.php  13
- main/auth/simplesamlphp/tests/lib/SimpleSAML/Utils/HTTPTest.php  3
- main/auth/simplesamlphp/lib/SimpleSAML/Metadata/MetaDataStorageHandlerPdo.php  8
- main/auth/simplesamlphp/modules/saml/lib/Error.php  4
- main/auth/simplesamlphp/modules/portal/lib/Portal.php  8
- main/auth/simplesamlphp/modules/core/lib/Stats/Output/File.php  3
- main/auth/simplesamlphp/tests/lib/SimpleSAML/XML/ParserTest.php  1
- main/auth/simplesamlphp/lib/SimpleSAML/Auth/Simple.php  14
- main/auth/simplesamlphp/lib/SimpleSAML/Logger/SyslogLoggingHandler.php  3
- main/auth/simplesamlphp/lib/SimpleSAML/Database.php  5
- main/auth/simplesamlphp/lib/SimpleSAML/Metadata/SAMLParser.php  28
- main/auth/simplesamlphp/lib/SimpleSAML/Store.php  7
- main/auth/simplesamlphp/tests/modules/core/lib/Auth/Process/AttributeLimitTest.php  1
- main/auth/simplesamlphp/lib/SimpleSAML/Utils/Crypto.php  9
- main/auth/simplesamlphp/lib/SimpleSAML/SessionHandler.php  2
- main/auth/simplesamlphp/tests/modules/core/lib/Auth/UserPassOrgBaseTest.php  1
- main/auth/simplesamlphp/modules/core/lib/Auth/Process/AttributeValueMap.php  11
- main/auth/simplesamlphp/modules/saml/lib/Message.php  42
- main/auth/simplesamlphp/lib/SimpleSAML/XHTML/Template.php  12
- main/auth/simplesamlphp/tests/modules/core/lib/Auth/Process/CardinalityTest.php  1
- main/auth/simplesamlphp/modules/saml/lib/Auth/Process/PersistentNameID2TargetedID.php  3
- main/auth/simplesamlphp/tests/www/IndexTest.php  1
- main/auth/simplesamlphp/tests/lib/SimpleSAML/Store/RedisTest.php  2
- main/auth/simplesamlphp/tests/lib/SimpleSAML/Auth/SimpleTest.php  1
- main/auth/simplesamlphp/modules/admin/lib/FederationController.php  22
- main/auth/simplesamlphp/modules/core/www/assets/js/loginuserpass.js  1
- main/auth/simplesamlphp/modules/saml/lib/BaseNameIDGenerator.php  8
- main/auth/simplesamlphp/tests/lib/SimpleSAML/StoreTest.php  1
- main/auth/simplesamlphp/lib/SimpleSAML/Store/Redis.php  4
- main/auth/simplesamlphp/modules/core/lib/Storage/SQLPermanentStorage.php  8
- main/auth/simplesamlphp/modules/saml/lib/Error/ProxyCountExceeded.php  1
- main/auth/simplesamlphp/modules/admin/lib/ConfigController.php  11
- main/auth/simplesamlphp/tests/lib/SimpleSAML/Auth/SourceTest.php  1
- main/auth/simplesamlphp/modules/core/lib/Auth/Process/LanguageAdaptor.php  6
- main/auth/simplesamlphp/tests/lib/SimpleSAML/Utils/ArraysTest.php  1
- main/auth/simplesamlphp/modules/admin/lib/TestController.php  17
- main/auth/simplesamlphp/modules/saml/lib/Error/NoAvailableIDP.php  1
- main/auth/simplesamlphp/modules/saml/lib/Auth/Process/PersistentNameID.php  6
- main/auth/simplesamlphp/modules/cron/hooks/hook_frontpage.php  1
- main/auth/simplesamlphp/tests/lib/SimpleSAML/XML/ValidatorTest.php  1
- main/auth/simplesamlphp/tests/lib/SimpleSAML/Locale/TranslateTest.php  1
- main/auth/simplesamlphp/modules/exampleauth/lib/Auth/Source/UserPass.php  5
- main/auth/simplesamlphp/modules/exampleauth/lib/Auth/Process/RedirectTest.php  1
- main/auth/simplesamlphp/lib/SimpleSAML/IdP.php  9
- main/auth/simplesamlphp/lib/SimpleSAML/Metadata/SAMLBuilder.php  34
- main/auth/simplesamlphp/tests/modules/core/lib/Auth/Process/AttributeMapTest.php  1
- main/auth/simplesamlphp/lib/SimpleSAML/XML/Shib13/AuthnRequest.php  2
- main/auth/simplesamlphp/modules/saml/lib/IdP/SQLNameID.php  5
- main/auth/simplesamlphp/tests/lib/SimpleSAML/Utils/CryptoTest.php  2
- main/auth/simplesamlphp/lib/SimpleSAML/Logger/StandardErrorLoggingHandler.php  1
- main/auth/simplesamlphp/tests/lib/SimpleSAML/Metadata/MetaDataStorageHandlerTest.php  1
- main/auth/simplesamlphp/tests/modules/saml/lib/Auth/Source/Auth_Source_SP_Test.php  2
- main/auth/simplesamlphp/modules/core/lib/Auth/Process/Cardinality.php  15
- main/auth/simplesamlphp/tests/lib/SimpleSAML/SessionHandlerPHPTest.php  1
- main/auth/simplesamlphp/lib/SimpleSAML/Utils/HTTP.php  15
- main/auth/simplesamlphp/tests/modules/core/lib/Auth/Process/AttributeCopyTest.php  1
- main/auth/simplesamlphp/www/_include.php  5
- main/auth/simplesamlphp/modules/saml/lib/IdP/SAML2.php  25
- main/auth/simplesamlphp/tests/lib/SimpleSAML/XML/ErrorsTest.php  1
- main/auth/simplesamlphp/tests/modules/multiauth/lib/Auth/Source/MultiAuthTest.php  3
- main/auth/simplesamlphp/lib/SimpleSAML/Bindings/Shib13/Artifact.php  5
- main/auth/simplesamlphp/lib/SimpleSAML/Error/CriticalConfigurationError.php  2
- main/auth/simplesamlphp/tests/modules/core/lib/Auth/Process/ScopeAttributeTest.php  1
- main/auth/simplesamlphp/lib/SimpleSAML/Metadata/MetaDataStorageHandlerFlatFile.php  4
- main/auth/simplesamlphp/tests/_autoload_modules.php  7
- main/auth/simplesamlphp/tests/lib/SimpleSAML/Utils/ConfigTest.php  1
- main/auth/simplesamlphp/modules/saml/lib/Error/NoPassive.php  1
- main/auth/simplesamlphp/lib/SimpleSAML/Utils/HttpAdapter.php  1
- main/auth/simplesamlphp/lib/SimpleSAML/Store/Memcache.php  2
- main/auth/simplesamlphp/lib/SimpleSAML/Error/Exception.php  5
- main/auth/simplesamlphp/modules/core/lib/Auth/Process/PHP.php  2
- main/auth/simplesamlphp/tests/Utils/TestAuthSource.php  1
- main/auth/simplesamlphp/modules/core/lib/Auth/Process/TargetedID.php  9
- main/auth/simplesamlphp/modules/admin/lib/Menu.php  1
- main/auth/simplesamlphp/lib/SimpleSAML/Error/ConfigurationError.php  3
- main/auth/simplesamlphp/lib/SimpleSAML/SessionHandlerCookie.php  4
- main/auth/simplesamlphp/src/js/bundle.js  2
- main/auth/simplesamlphp/tests/SigningTestCase.php  1
- main/auth/simplesamlphp/tests/BuiltInServer.php  6
- main/auth/simplesamlphp/lib/SimpleSAML/Auth/ProcessingChain.php  7
- main/auth/simplesamlphp/tests/modules/saml/lib/IdP/SQLNameIDTest.php  1
- main/auth/simplesamlphp/modules/core/lib/ACL.php  9
- main/auth/simplesamlphp/tests/lib/SimpleSAML/Utils/Config/MetadataTest.php  23
- main/auth/simplesamlphp/modules/saml/lib/Auth/Process/TransientNameID.php  1
- main/auth/simplesamlphp/modules/saml/lib/Auth/Process/FilterScopes.php  12
- main/auth/simplesamlphp/modules/core/hooks/hook_sanitycheck.php  8
- main/auth/simplesamlphp/templates/post.php  3
- main/auth/simplesamlphp/modules/exampleauth/lib/Auth/Source/StaticSource.php  2
- main/auth/simplesamlphp/tests/Utils/ClearStateTestCase.php  2
- main/auth/simplesamlphp/lib/SimpleSAML/HTTP/RunnableResponse.php  1
- main/auth/simplesamlphp/lib/SimpleSAML/Metadata/MetaDataStorageHandler.php  12
- main/auth/simplesamlphp/templates/includes/attributes.php  17
- main/auth/simplesamlphp/tests/lib/AutoloadModulesTest.php  1
- main/auth/simplesamlphp/modules/core/hooks/hook_frontpage.php  1
- main/auth/simplesamlphp/tests/modules/core/lib/Auth/Process/PHPTest.php  1
- main/auth/simplesamlphp/tests/www/TemplateTest.php  9
- main/auth/simplesamlphp/tests/modules/core/lib/Auth/Process/AttributeAddTest.php  1
- main/auth/simplesamlphp/tests/lib/SimpleSAML/Utils/TimeTest.php  5
- main/auth/simplesamlphp/tests/lib/SimpleSAML/Utils/SystemTest.php  2
- main/auth/simplesamlphp/modules/portal/hooks/hook_htmlinject.php  3
- main/auth/simplesamlphp/tests/modules/saml/lib/Auth/Process/FilterScopesTest.php  1
- main/auth/simplesamlphp/lib/SimpleSAML/SessionHandlerStore.php  4
- main/auth/simplesamlphp/modules/core/lib/Auth/Process/CardinalitySingle.php  9
- main/auth/simplesamlphp/lib/SimpleSAML/Logger.php  12
- main/auth/simplesamlphp/modules/cron/lib/Cron.php  3
- main/auth/simplesamlphp/lib/SimpleSAML/Error/UnserializableException.php  2
- main/auth/simplesamlphp/modules/saml/lib/Auth/Source/SP.php  33
- main/auth/simplesamlphp/www/resources/jquery-1.8.js  60
- main/auth/simplesamlphp/modules/exampleauth/lib/Auth/Source/External.php  5
- main/auth/simplesamlphp/lib/SimpleSAML/Module.php  25
- main/auth/simplesamlphp/lib/SimpleSAML/Store/SQL.php  9
- main/auth/simplesamlphp/tests/Utils/SpTester.php  1
- main/auth/simplesamlphp/lib/SimpleSAML/Error/Assertion.php  2
- main/auth/simplesamlphp/tests/lib/SimpleSAML/Metadata/MetaDataStorageSourceTest.php  1
- main/auth/simplesamlphp/lib/SimpleSAML/Utils/Arrays.php  6
- main/auth/simplesamlphp/lib/SimpleSAML/Auth/DefaultAuth.php  2
- main/auth/simplesamlphp/tests/modules/core/lib/Storage/SQLPermanentStorageTest.php  1
- main/auth/simplesamlphp/modules/saml/lib/Auth/Process/ExpectedAuthnContextClassRef.php  2
- main/auth/simplesamlphp/lib/SimpleSAML/Utils/XML.php  12
- main/auth/simplesamlphp/tests/modules/core/lib/Auth/Process/AttributeValueMapTest.php  1
- main/auth/simplesamlphp/tests/modules/saml/lib/Auth/Process/NameIDAttributeTest.php  1
- main/auth/simplesamlphp/tests/lib/SimpleSAML/Store/SQLTest.php  1
- main/auth/simplesamlphp/lib/SimpleSAML/Module/ControllerResolver.php  6
- main/auth/simplesamlphp/tests/lib/SimpleSAML/Utils/XMLTest.php  1
- main/auth/simplesamlphp/tests/lib/SimpleSAML/Metadata/SAMLBuilderTest.php  5
- main/auth/simplesamlphp/lib/SimpleSAML/Session.php  12
- main/auth/simplesamlphp/src/js/logout/main.js  1
- main/auth/simplesamlphp/tests/lib/SimpleSAML/Utils/EMailTestCase.php  1
- main/auth/simplesamlphp/lib/SimpleSAML/Auth/TimeLimitedToken.php  3
- main/auth/simplesamlphp/lib/SimpleSAML/IdP/IFrameLogoutHandler.php  6
- main/auth/simplesamlphp/lib/SimpleSAML/Metadata/Signer.php  10
- main/auth/simplesamlphp/lib/SimpleSAML/Error/BadRequest.php  1
- main/auth/simplesamlphp/www/resources/post.js  1
- main/auth/simplesamlphp/lib/SimpleSAML/Utils/System.php  10
- main/auth/simplesamlphp/modules/multiauth/lib/Auth/Source/MultiAuth.php  10
- main/auth/simplesamlphp/tests/modules/core/lib/Auth/Process/AttributeAlterTest.php  1
- main/auth/simplesamlphp/modules/saml/lib/Auth/Process/AuthnContextClassRef.php  2
- main/auth/simplesamlphp/modules/core/lib/Controller/Exception.php  3
- main/auth/simplesamlphp/lib/SimpleSAML/Utils/Net.php  10
- main/auth/simplesamlphp/tests/modules/core/lib/Auth/Process/CardinalitySingleTest.php  1
- main/auth/simplesamlphp/tests/lib/SimpleSAML/ModuleTest.php  1
- main/auth/simplesamlphp/modules/core/lib/Auth/Process/AttributeAlter.php  18
- main/auth/simplesamlphp/tests/modules/core/lib/Auth/Process/TargetedIDTest.php  1
- main/auth/simplesamlphp/modules/core/lib/Auth/Process/GenerateGroups.php  7
- main/auth/simplesamlphp/tests/lib/SimpleSAML/Metadata/SAMLParserTest.php  3
- main/auth/simplesamlphp/lib/SimpleSAML/Locale/Language.php  6
- main/auth/simplesamlphp/lib/SimpleSAML/Bindings/Shib13/HTTPPost.php  6
- main/auth/simplesamlphp/lib/SimpleSAML/XHTML/IdPDisco.php  12
- main/auth/simplesamlphp/lib/SimpleSAML/Error/NotFound.php  2
- main/auth/simplesamlphp/lib/SimpleSAML/Metadata/MetaDataStorageHandlerXML.php  12
- main/auth/simplesamlphp/lib/SimpleSAML/Metadata/MetaDataStorageHandlerSerialize.php  7
- main/auth/simplesamlphp/tests/lib/SimpleSAML/XML/Shib13/AuthnResponseTest.php  1
- main/auth/simplesamlphp/modules/core/lib/Auth/Process/ExtendIdPSession.php  5
- main/auth/simplesamlphp/modules/saml/lib/Error/NoAuthnContext.php  1
- main/auth/simplesamlphp/lib/SimpleSAML/Locale/Localization.php  5
- main/auth/simplesamlphp/modules/core/lib/Auth/Process/AttributeCopy.php  5
- main/auth/simplesamlphp/modules/cron/hooks/hook_cron.php  2
- main/auth/simplesamlphp/lib/SimpleSAML/Logger/FileLoggingHandler.php  5
- main/auth/simplesamlphp/lib/SimpleSAML/Locale/Translate.php  8
- main/auth/simplesamlphp/tests/lib/SimpleSAML/Auth/StateTest.php  1
- main/auth/simplesamlphp/tests/Utils/StateClearer.php  3
- main/auth/simplesamlphp/lib/SimpleSAML/Utilities.php  5
- main/auth/simplesamlphp/lib/SimpleSAML/Error/NoState.php  1
- main/auth/simplesamlphp/lib/SimpleSAML/Utils/Time.php  15
- main/auth/simplesamlphp/modules/saml/hooks/hook_metadata_hosted.php  4
- main/auth/simplesamlphp/tests/lib/SimpleSAML/Utils/AttributesTest.php  1
- main/auth/simplesamlphp/modules/core/lib/Controller/Login.php  7
- main/auth/simplesamlphp/modules/saml/lib/Auth/Process/NameIDAttribute.php  7
- main/auth/simplesamlphp/lib/SimpleSAML/Metadata/Sources/MDQ.php  11
- main/auth/simplesamlphp/modules/core/lib/Auth/Process/AttributeRealm.php  3
- main/auth/simplesamlphp/lib/SimpleSAML/Error/Error.php  6
- main/auth/simplesamlphp/bin/memcacheSync.php  12
- main/auth/simplesamlphp/lib/SimpleSAML/Auth/Source.php  5
- main/auth/simplesamlphp/modules/saml/lib/Error/NoSupportedIDP.php  1
- main/auth/external_login/okta.inc.php  6
- main/auth/simplesamlphp/lib/SimpleSAML/Auth/State.php  6
- main/auth/simplesamlphp/tests/modules/saml/lib/IdP/SAML2Test.php  1
- main/auth/simplesamlphp/src/js/logout/logout.js  8
- main/auth/simplesamlphp/modules/saml/lib/SP/LogoutStore.php  19
- main/auth/simplesamlphp/tests/Utils/ReduceSpillOverTest.php  2
- main/auth/simplesamlphp/tests/lib/SimpleSAML/Utils/RandomTest.php  1
- main/auth/simplesamlphp/modules/saml/lib/Auth/Process/SQLPersistentNameID.php  10
- main/auth/simplesamlphp/lib/SimpleSAML/Utils/Random.php  1
- main/auth/simplesamlphp/modules/saml/lib/Auth/Process/AttributeNameID.php  4
- main/auth/simplesamlphp/tests/modules/core/lib/Controller/LoginControllerTest.php  1
- main/auth/simplesamlphp/modules/core/lib/Auth/Process/ScopeFromAttribute.php  4
- main/auth/simplesamlphp/modules/saml/lib/IdP/SAML1.php  11
- main/auth/simplesamlphp/modules/core/lib/Auth/Process/AttributeAdd.php  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/chamilo/chamilo-lms/pullRequest?prid=5738742&bid=18771963)

**Comment by ywarnier** [comment]
The fact that you include the whole simplesaml makes it complicated to integrate. As far as I can see, you can actually get it through composer, so we could just add it as a dependency and it would be included in the autoload.
Assigning to @AngelFQC for cleanup.

**Comment by ywarnier** [comment]
Contacted @FraGoTe and waiting for a review of this PR and a possible switch to onelogin/php-saml

**Comment by ywarnier** [comment]
@FraGoTe ping

**Comment by ywarnier** [comment]
@FraGoTe hemos (@jmontoyaa en este caso) iniciado un trabajo de limpieza de tu PR en https://github.com/chamilo/chamilo-lms/pull/3390 pero luego de unas pruebas e investigaciones, parece que OKTA permite usar openid/saml/SWA y en este caso se podría muy bien usar SAML con la librería que ya tenemos en interno (de lo cual se puede ver un ejemplo aquí: https://github.com/chamilo/chamilo-lms/blob/1.11.x/main/auth/okn/start.php), por lo que no vemos la necesidad de incluir este PR.

**Pull request closed without merging**
