### PR TITLE
In reports: add new line to show followed student' superiors. Also fix some bugs.

### PR DESCRIPTION
**Pull request by dnos**
- In reports, add new line to show followed student' superiors.
- Fix bug showing total number of users followed, as well as number of rrhh resp. followed (when no students were followed the number of rrhh resp. was always zero).
- Add new text label: $FollowedStudentBosses (translated to catalan, spanish and english)

### CODE REVIEW

**Comment by dnos** [comment]
In the reports section there is a list to show:
- Students followed
- Teachers followed
- RRHH resp. followed
- Users followed (this includes all the users, including student superiors)

A new line in the html table has been added as well as the code needed in main/inc/lib/tracking.lib.php to calculate the superiors of students that the user is following.

Bugs fixed:
- When the user was not following any student, then the showed number of RRHH resp. followed was always 0 (although some resp. were actually followed).
- The total number of followed users was incorrect, as the student's superiors were never counted in the sum, although they were showed in the users followed list.

New label text added in catalan, spanish and english (FollowedStudentBosses):
"Superiors d'estudiant seguits"
"Superiores de estudiante seguidos"
"Followed student' superiors"

**Comment by ywarnier** [comment]
@dnos, we send language variables through another channel. Could you resend your PR without any main/lang/ change please? We'll take care of the language term based on your comment.

**Comment by dnos** [comment]
@ywarnier ok, I didn't know that, I have added a commit that removes the label created in the language files.

**Comment by ywarnier** [comment]
Better, but your PR still includes main/lang/english/trad4all.inc.php and main/lang/spanish/trad4all.inc.php. I'll merge manually directly with the language files from the translate application to avoid issues.
The rest is quite good. Thanks!
You can find our coding conventions in the CONTRIBUTING.md file.

**Pull request merged**
