### PR TITLE
Fix function is certificate available

### PR DESCRIPTION
**Pull request by miky96es**
#1938

### CODE REVIEW

**Comment by hi-rafa** [comment]
The problem was that the function calc_score() in file main/gradebook/lib/be/learnpathlink.class.php
was always searching the data in LP_VIEW table by the wrong SESSION_ID.

`SELECT * FROM c_lp_view 
WHERE
c_id = 1 AND 
lp_id = 1 AND
session_id = 0 AND 
user_id = 3 
ORDER BY view_count DESC`

The session_id value shouldn't be always obtained from $_session['id_session'] because it would limit its functionality. 

`$session_id = api_get_session_id();`

## Solution
Sometimes we need to pass the session_id value throw the class attribute that's why we added this code.
`$session_id = (api_get_session_id()==0)? $this->get_session_id() : api_get_session_id();`

The function calc_score()  in file main/gradebook/lib/be/exerciselink.class.php obtains the value directly from the attribute class.

`$session_id = $this->get_session_id()`

**Comment by hi-rafa** [comment]
screen shot 2017-05-11 at 10 06 36 am
screen shot 2017-05-11 at 10 11 10 am

screen shot 2017-05-11 at 10 12 44 am

screen shot 2017-05-11 at 10 18 35 am

screen shot 2017-05-11 at 11 35 32 am

screen shot 2017-05-11 at 11 35 53 am

**Comment by AngelFQC** [comment]
Please clean off your pull request of merge commits. And rename properly the commit "#1938"

**Comment by hi-rafa** [comment]
Hi @AngelFQC 
I know isn't my commit but I don't understand what you mean.
How  to clean off the  pull request of merge commits?
What do you mean by renaming  properly the commit?
thank you

**Comment by AngelFQC** [comment]
Hi @hi-rafa 
I mean that you do not have to send the merge commits, send the commit (s) with you're fixing the bug (like the commit 3190ef8)
And rename the 3190ef8 commit, because its message only say "#1938". You can rename it with `git rebase` in your local repo

**Comment by ywarnier** [comment]
He añadido este commit que creo que es lo único necesario, para intentar resolver el problema aquí: https://github.com/chamilo/chamilo-lms/commit/352bb6a2df04e9e838d782328c3c0814d5e1b738.
Podrías revisar si te parece bien @miky96es y así cerrar este PR de aquí que está mal formado?

**Comment by hi-rafa** [comment]
Hola @ywarnier 
Añadí el ternario porque no me conozco toda la aplicacion y tenia miedo que al cambiarlo dejara de funcionar en otro parte pero si tu crees que el ternario no es necesario entonces a nosotros no parece bien.

**Comment by ywarnier** [comment]
Perdón, no lo había notado. Lo agregué de otra manera que me parece más correcta (que primero recupera el session_id del objeto y *luego* (si no encuentra) pasa a la sesión PHP.

**Comment by hi-rafa** [comment]
Hola @AngelFQC 
Este pull request ya no hace falta limpiar los merge correcto ya que ha sido cerrado?

**Comment by AngelFQC** [comment]
@hi-rafa No, ya no. Ya se aplicó el commit individualmente 😄

**Pull request closed without merging**
