### PR TITLE
Fix Drag & drop multiUpload Click Event in Chrome Browser - Refs #8049

### PR DESCRIPTION
**Pull request by jloguercio**

### CODE REVIEW

**Comment by ywarnier** [comment]
@aragonc puedes verificar este cambio de CSS (que no afecte otra cosa)?

**Comment by aragonc** [comment]
Merece un Like

**Comment by jloguercio** [comment]
:v:

**Comment by ywarnier** [comment]
@jloguercio can you send it to master as well?

**Comment by jloguercio** [comment]
Here : https://github.com/chamilo/chamilo-lms/pull/994

**Pull request merged**
