### PR TITLE
GDPR fields titles in Terms and Conditons should be invisbile if there is no content

### PR DESCRIPTION
**Pull request by carlangas159**
GDPR fields titles in Terms and Conditons should be invisbile if there is no content - ref #3437

### CODE REVIEW

**Comment by carlangas159** [comment]
> GDPR fields titles in Terms and Conditons should be invisbile if there is no content - ref #3437

image

**Comment by ywarnier** [comment]
@NicoDucou this change seems rather simple. Could you check it on a system with GDPR items already set? (and also check why in Carlos' screenshot, there is an untranslated term - is this one missing?)

**Comment by NicoDucou** [comment]
The change is correct and it works fine with already set GDPR content and without content.
For the translation, it's because of a missing get_lang so none of the title where translated.
I accept this PR and then I correct the get_lang issue.

**Comment by NicoDucou** [comment]
Fixed with commit 107d15f9f8b739a3cca1183ebe746a79d43d207b

**Pull request merged**
