### PR TITLE
remove line-break filtering on save after editing

### PR DESCRIPTION
**Pull request by mk111**
obvious legacy piece of code: currently prevents line breaks in case of entering program code in '<code>' and '<pre>' blocks so it should be removed. Filtering should be implemented inside editor itself.

### CODE REVIEW

**Comment by ywarnier** [comment]
Legacy indeed... I could trace it back to 15 years ago, but I'm not sure why it's been added initially (the commit message is unrelated and affects 4500 files so even Github doesn't want to show the details).
https://github.com/chamilo/chamilo-lms/blame/3412f6e28d0bcd88a9eeff6cfaa3eccc77fab57d/main/document/edit_document.php#L334

I assume you tested that in your use case @mk111  and that works well for all practical scenarios?

**Comment by mk111** [comment]
if a html document is created with preformatted block, **format is preserved** after editing ( by edit_document.php ). 

But just as it is mentioned and just for documents.  Since change is NOT related to the ckeditor itself, format is not preserved, for example, when switching from wysiwg to source and vice-versa; that's ckeditor (and some templates?) configuration.  

---

as for code in document:

i can see codesnippet plugin with highlight,js in the (one of the) ckeditor plugin repository, but there is no 'template'  to select for inserting  
```html
<pre><code>
```
sequence/block  to enable code inserting with plugin and proper hiliting. 

And then; hilight.js have to be loaded to resulting html source even if there is no ckeditor loaded (view html) to 'color' the code.

---

**Comment by ywarnier** [comment]
Thanks for your contribution

**Comment by AngelFQC** [comment]
> And then; hilight.js have to be loaded to resulting html source even if there is no ckeditor loaded (view html) to 'color' the code.

This is related to #2794

**Comment by mk111** [comment]
ye, there is my prototype template :

```html
<!DOCTYPE html>
<html>
<head><meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>CodeTemplate</title>
	<link href="https://***/web/assets/bootstrap/dist/css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css" />
	<title></title>
	<link href="https://***/web/assets/bootstrap/dist/css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css" />
	<title></title>
	<link href="https://***/web/assets/bootstrap/dist/css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css" />
	<title></title>
	<link href="https://***/web/assets/bootstrap/dist/css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css" />
	<title></title>
	<link href="https://***/web/assets/bootstrap/dist/css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css" />
	<title></title>
	<link href="https://***/web/assets/bootstrap/dist/css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css" />
	<link href="https://***/web/assets/bootstrap/dist/css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css" />
	<link href="https://***/web/assets/fontawesome/css/font-awesome.min.css" media="screen" rel="stylesheet" type="text/css" />
	<link href="https://***/web/css/document.css" media="screen" rel="stylesheet" type="text/css" />
	<link href="https://***/web/assets/ckeditor/plugins/codesnippet/lib/highlight/styles/xcode.css" media="screen" rel="stylesheet" type="text/css" />
	<title></title>
</head>
<meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<script src="https://***/web/assets/ckeditor/plugins/codesnippet/lib/highlight/highlight.pack.js"></script>
<body>
<p>Introduction</p>

<pre style="display: inline-block">
<code language="java">
void lineOfCode(){return;}
</code></pre>

<p>if you want another block, just copy one of those</p>

<pre style="display: inline-block">
<code language="java">
void lineOfCode2(){return;}
</code></pre>

<p>footer text</p>
<script>
//hljs.highlightAll();
hljs.initHighlightingOnLoad();
</script></body>
</html>
```
old-style loading at the bottom, hilite.js library loaded from existing web/assets/ckeditor/plugins/codesnippet/lib/highlight/highlight.pack.js  and using xcode.css as a style.

-------------------------------
if upper can be used, following represent failure while try to editing content. Rendering final markdown with remark.js is but ok.


```html
<!DOCTYPE html>
<html>
<head><meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>[=MarkupSlides=]</title>
	<link href="https://***/web/assets/bootstrap/dist/css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css" />
	<title></title>
	<link href="https://***/web/assets/bootstrap/dist/css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css" />
	<link href="https://***/web/assets/bootstrap/dist/css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css" />
	<link href="https://***/web/assets/fontawesome/css/font-awesome.min.css" media="screen" rel="stylesheet" type="text/css" />
	<link href="https://***/web/css/document.css" media="screen" rel="stylesheet" type="text/css" />
	<title></title>
	<style type="text/css">@import url(https://fonts.googleapis.com/css?family=Yanone+Kaffeesatz);
      @import url(https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic);
      @import url(https://fonts.googleapis.com/css?family=Ubuntu+Mono:400,700,400italic);

      body { font-family: 'Droid Serif'; }
      h1, h2, h3 {
        font-family: 'Yanone Kaffeesatz';
        font-weight: normal;
      }
      .remark-code, .remark-inline-code { font-family: 'Ubuntu Mono'; }
	</style>
</head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<body>
<p><textarea id="source">class: center, middle

# Title
markdown to slide(s)

---

# Agenda

1. Introduction
2. Deep-dive
3. ...

---

# Introduction
</textarea>
<script src="https://remarkjs.com/downloads/remark-latest.min.js">
    </script><script>
      var slideshow = remark.create();
    </script></p>
</body>
</html>

```

**Comment by AngelFQC** [comment]
@mk111 I sent this commit a48055c13f5faad3be5a941be8b4c53c89977dbe to load highlight.js inside ckeditor and documents created with ckeditor.

You can check it here https://11.chamilo.org/main/document/showinframes.php?cidReq=11TEST&id_session=0&gidReq=0&gradebook=0&origin=&id=13241 (admin/admin)

**Comment by mk111** [comment]
very nice. PDF from html is also generated well. 
------------
just to mention: source inside 'pre - code' is not bullet-proof protected; when using templates, styles from templates overrides those from hilite.js. Example : create new document, apply template that define a table, insert code into any cell ....  
I would not fix that: possibility to one using such template and code insertion in the same document, and mix them, equals (almost) 0. 
-------------

**Pull request merged**
