### PR TITLE
Implementation of api_get_language_isocode

### PR DESCRIPTION
**Pull request by SatyanJ**
`api_get_interface_language` is deprecated and replace with `api_get_language_isocode`.
This function shall return the isocode of the platform language.
(fix for #1891)

(cc @moy)

### CODE REVIEW

**Comment by jmontoyaa** [comment]
There's no need to do that change.

`Container::getTranslator()->getLocale();`

That code is in charge to return the locale of the platform.
The locale value is changed depending on on the listener here:
`
src/Chamilo/CoreBundle/EventListener/LocaleListener.php`

This is the place where the locale changes depending some parameters (user/platform/course/etc).

**Comment by SatyanJ** [comment]
I got an error when trying to display a course, `Container::getTranslator()->getLocale();` returns 'english' instead of 'en'.

**Comment by jmontoyaa** [comment]
That's then an error.

In which page, URL? 

I have currently "en" when entering to:

"web/app_dev.php/main/admin/course_list.php" or
"web/app_dev.php/userportal"

Did you check that you have correctly the locale in:

`app/config/parameters.yml`

**Comment by SatyanJ** [comment]
It might be link to the use of the course filler. When I use it and click on a generated course there an error but with a manually created course it's ok.

**Comment by jmontoyaa** [comment]
I just added a fix for the course filler.

**Pull request closed without merging**
